[build]
  base = "dolar-app-final"
  publish = "dolar-app-final"
  functions = "dolar-app-final/netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
